name: Node.js CI

on:
  push:
    branches:
      - main  feature/mayssabejaoui/add-docker-build-push-step-to-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
   
    - name: Build Docker image
      run: |
        docker build -t image1:latest .
      working-directory: ./  

    - name: Log in to Docker Hub
      run: docker login -u mayssabejaoui -p narnarnar2019

    - name: Push Docker image
      run: |
        docker push image1:latest
      working-directory: ./

    - name: Cleanup Docker credentials
      run: docker logout