name: Node.js CI

on:
  push:
    branches:
      - feature/methni-sourour/add-docker-build-push-step-to-ci  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker build -t sourour-image:v1 .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push sourour-image:v1

    - name: Create Docker image PR
      run: |
        git config user.name "sourour"
        git config user.email "sourour.methhni@email.com"
        git checkout -b feature/methni-sourour/docker-image
        git add -A
        git commit -m "Add Docker image"
        git push origin feature/methni-sourour/docker-image
